/*
 * Header file for common function between encoding and decoding
 * 
 * Author: Jakub Wlodek
 * Created 5/16/18
 */

#ifndef COMMON_H
#define COMMON_H

/*
 * Struct used to store set of alphabets generated by a particular key.
 * Used for second encoding phase and first decoding phase
 */
struct alphabet_set{
    int num_alphas;
    char** alphas;
};

char* remove_duplicates(char* key);

char* get_transpose_alpha(char* key, int width);

void print_alphabets(char** alphabets, int num);

char get_pos(char c, char* alphabet);

struct alphabet_set* create_alphabets_on_key(char* key);

#endif /* COMMON_H */